title: Danielle A. Ripsman
email: your-email@domain.com
description: "Ph.D. in Management Science & Engineering. <br> Specializing in Operations Research and Radiation Therapy treatment planning."
baseurl: "" 
url: "https://danirip.github.io"
github_username: danirip
