title: Danielle A. Ripsman
email: dripsma1 [at] jh.edu
description: "Ph.D. in Management Science & Engineering <br> Operations Research | Healthcare Applications | Analytics & Optimization"
baseurl: "" 
url: "https://danirip.github.io"
github_username: danirip
